"""
FCA Consumer Duty recourse reporting.

Generates structured audit records (JSON-serialisable dict) and
customer-facing HTML explanations from a list of RecourseAction objects.

The SHA-256 audit hash covers model metadata, factual feature values, and
all recourse action details, providing a tamper-evident record suitable for
regulatory audit under Consumer Duty PS22/9.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

import pandas as pd

from insurance_recourse.generator import RecourseAction


class RecourseReport:
    """
    FCA Consumer Duty recourse explanation report.

    Produces structured output (JSON audit dict) and a customer-facing HTML
    page explaining how a policyholder could reduce their premium. The audit
    hash provides a tamper-evident record for regulatory purposes.

    Parameters
    ----------
    factual:
        Original policyholder feature vector.
    actions:
        Recourse actions generated by RecourseGenerator.generate().
    model_metadata:
        Free-form dict of model versioning information. Recommended keys:
        'model_version', 'product', 'effective_date'.
    policyholder_id:
        Optional reference identifier (anonymised for customer-facing output).
    current_premium:
        Current annual premium in GBP.
    generated_at:
        Override the report timestamp (ISO 8601 string). Defaults to now.

    Examples
    --------
    >>> report = RecourseReport(
    ...     factual=factual_series,
    ...     actions=recourse_actions,
    ...     model_metadata={"model_version": "2024-Q4-motor-v3", "product": "motor"},
    ...     policyholder_id="POL-123456",
    ...     current_premium=1450.0,
    ... )
    >>> audit_dict = report.to_dict()
    >>> html_page = report.to_html()
    """

    def __init__(
        self,
        factual: pd.Series,
        actions: List[RecourseAction],
        model_metadata: Dict[str, Any],
        policyholder_id: Optional[str] = None,
        current_premium: Optional[float] = None,
        generated_at: Optional[str] = None,
    ) -> None:
        self.factual = factual
        self.actions = actions
        self.model_metadata = model_metadata
        self.policyholder_id = policyholder_id
        self._generated_at = generated_at or datetime.now(timezone.utc).isoformat()

        # Infer current_premium from actions if not provided
        if current_premium is not None:
            self.current_premium = current_premium
        elif actions:
            # Back-calculate from first action
            a = actions[0]
            self.current_premium = round(a.predicted_premium + a.premium_reduction, 2)
        else:
            self.current_premium = 0.0

    def _build_recourse_options(self) -> List[Dict[str, Any]]:
        options = []
        for rank, action in enumerate(self.actions, start=1):
            entry: Dict[str, Any] = {
                "rank": rank,
                "description": action.description or self._fallback_description(action),
                "premium_after": round(action.predicted_premium, 2),
                "saving_gbp": round(action.premium_reduction, 2),
                "saving_pct": round(action.premium_reduction_pct, 1),
                "estimated_cost_gbp": round(action.effort.monetary_cost, 2),
                "implementation_days": round(action.effort.time_days, 0),
                "feasibility_pct": round(action.effort.feasibility_probability * 100, 1),
                "feature_changes": {
                    k: {"from": v[0], "to": v[1]}
                    for k, v in action.feature_changes.items()
                },
                "causal_effects": action.causal_effects,
                "validity": action.validity,
            }
            options.append(entry)
        return options

    @staticmethod
    def _fallback_description(action: RecourseAction) -> str:
        if not action.feature_changes:
            return "No changes required."
        parts = [
            f"{k}: {v[0]} → {v[1]}" for k, v in action.feature_changes.items()
        ]
        return "; ".join(parts)

    def _compute_audit_hash(self, payload: dict) -> str:
        """SHA-256 hash over the serialised report payload."""
        serialised = json.dumps(payload, sort_keys=True, default=str).encode("utf-8")
        return hashlib.sha256(serialised).hexdigest()

    def to_dict(self) -> Dict[str, Any]:
        """
        Return a JSON-serialisable audit record.

        Structure conforms to the FCA Consumer Duty data specification for
        algorithmic decision explanations. The audit_hash field covers all
        fields except itself.
        """
        options = self._build_recourse_options()
        payload: Dict[str, Any] = {
            "policyholder_id": self.policyholder_id,
            "generated_at": self._generated_at,
            "model_metadata": self.model_metadata,
            "current_premium_gbp": round(self.current_premium, 2),
            "factual_features": {
                k: (float(v) if _is_numeric(v) else v)
                for k, v in self.factual.to_dict().items()
            },
            "recourse_options": options,
            "n_options": len(options),
        }
        payload["audit_hash"] = self._compute_audit_hash(payload)
        return payload

    def to_html(self) -> str:
        """
        Return a customer-facing HTML explanation page.

        Fully self-contained (inline CSS, no external dependencies). Suitable
        for embedding in a policyholder portal or rendering as a PDF.
        """
        options = self._build_recourse_options()
        model_version = self.model_metadata.get("model_version", "unknown")
        product = self.model_metadata.get("product", "insurance")
        ref = self.policyholder_id or "N/A"

        rows_html = ""
        for opt in options:
            feasibility_colour = (
                "#27ae60" if opt["feasibility_pct"] >= 70
                else "#e67e22" if opt["feasibility_pct"] >= 40
                else "#c0392b"
            )
            rows_html += f"""
            <tr>
                <td class="rank">{opt['rank']}</td>
                <td class="description">{opt['description']}</td>
                <td class="currency">£{opt['premium_after']:,.2f}</td>
                <td class="saving">
                    <span class="saving-badge">
                        £{opt['saving_gbp']:,.2f}
                        <span class="saving-pct">({opt['saving_pct']:.1f}%)</span>
                    </span>
                </td>
                <td class="currency">
                    {'£' + f"{opt['estimated_cost_gbp']:,.2f}" if opt['estimated_cost_gbp'] > 0 else 'None'}
                </td>
                <td>{int(opt['implementation_days'])}&nbsp;days</td>
                <td>
                    <span class="feasibility-badge" style="color:{feasibility_colour}">
                        {opt['feasibility_pct']:.0f}%
                    </span>
                </td>
                <td>
                    <span class="validity {'valid' if opt['validity'] else 'invalid'}">
                        {'&#10003;' if opt['validity'] else '&#10007;'}
                    </span>
                </td>
            </tr>"""

        no_options_msg = ""
        if not options:
            no_options_msg = """
            <div class="no-options">
                <p>No recourse options were found within your specified constraints.
                Please contact us to discuss your pricing in more detail.</p>
            </div>"""

        intro_msg = (
            f"Your current {product} premium is <strong>£{self.current_premium:,.2f}</strong> "
            f"per year. The table below shows changes you could consider to reduce your premium. "
            f"These are suggestions only — we are not able to guarantee savings, as premiums "
            f"depend on many factors. This information is provided under the FCA Consumer Duty "
            f"(PS22/9) to help you understand how your premium is calculated."
        )

        table_section = ""
        if options:
            table_section = f"""
            <table>
                <thead>
                    <tr>
                        <th>Rank</th>
                        <th>What you could change</th>
                        <th>New premium</th>
                        <th>Saving</th>
                        <th>Estimated cost</th>
                        <th>Timescale</th>
                        <th>Feasibility</th>
                        <th>Valid</th>
                    </tr>
                </thead>
                <tbody>
                    {rows_html}
                </tbody>
            </table>"""

        audit_hash = self._compute_audit_hash(self.to_dict())

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Premium Reduction Options — Consumer Duty Explanation</title>
    <style>
        *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}

        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
                         'Helvetica Neue', Arial, sans-serif;
            font-size: 14px;
            line-height: 1.6;
            color: #2c3e50;
            background: #f7f9fc;
        }}

        .container {{
            max-width: 1100px;
            margin: 32px auto;
            padding: 0 24px;
        }}

        .header {{
            background: #1a3a5c;
            color: #ffffff;
            padding: 28px 32px;
            border-radius: 8px 8px 0 0;
        }}

        .header h1 {{
            font-size: 22px;
            font-weight: 600;
            letter-spacing: -0.3px;
        }}

        .header .subtitle {{
            font-size: 13px;
            opacity: 0.75;
            margin-top: 4px;
        }}

        .meta-bar {{
            display: flex;
            gap: 32px;
            background: #2c5282;
            color: #e2e8f0;
            padding: 12px 32px;
            font-size: 12px;
        }}

        .meta-bar span strong {{
            color: #ffffff;
        }}

        .card {{
            background: #ffffff;
            border: 1px solid #e2e8f0;
            border-top: none;
            border-radius: 0 0 8px 8px;
            padding: 28px 32px;
        }}

        .intro {{
            background: #eaf4fb;
            border-left: 4px solid #2980b9;
            padding: 14px 18px;
            border-radius: 0 4px 4px 0;
            margin-bottom: 24px;
            font-size: 13.5px;
            color: #1a3a5c;
        }}

        table {{
            width: 100%;
            border-collapse: collapse;
            font-size: 13px;
        }}

        thead th {{
            background: #f0f4f8;
            color: #4a5568;
            font-weight: 600;
            text-transform: uppercase;
            font-size: 11px;
            letter-spacing: 0.5px;
            padding: 10px 12px;
            text-align: left;
            border-bottom: 2px solid #cbd5e0;
        }}

        tbody tr {{
            border-bottom: 1px solid #edf2f7;
            transition: background 0.15s;
        }}

        tbody tr:hover {{ background: #f7fafc; }}

        tbody td {{
            padding: 11px 12px;
            vertical-align: middle;
        }}

        td.rank {{
            font-weight: 700;
            color: #2980b9;
            font-size: 15px;
            text-align: center;
        }}

        td.description {{
            max-width: 280px;
            color: #2d3748;
        }}

        td.currency {{
            font-variant-numeric: tabular-nums;
            text-align: right;
        }}

        td.saving {{
            text-align: right;
        }}

        .saving-badge {{
            display: inline-block;
            background: #e6f4ea;
            color: #1e7e34;
            font-weight: 600;
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 12.5px;
        }}

        .saving-pct {{
            font-weight: 400;
            font-size: 11px;
            opacity: 0.8;
        }}

        .feasibility-badge {{
            font-weight: 700;
            font-size: 13px;
        }}

        .validity.valid  {{ color: #27ae60; font-size: 16px; font-weight: 700; }}
        .validity.invalid {{ color: #c0392b; font-size: 16px; font-weight: 700; }}

        .no-options {{
            background: #fff8e1;
            border-left: 4px solid #f39c12;
            padding: 14px 18px;
            border-radius: 0 4px 4px 0;
            color: #7d6608;
            font-size: 13.5px;
        }}

        .footer {{
            margin-top: 28px;
            padding: 16px 0;
            border-top: 1px solid #e2e8f0;
            font-size: 11px;
            color: #a0aec0;
            display: flex;
            justify-content: space-between;
            flex-wrap: wrap;
            gap: 8px;
        }}

        .audit-hash {{
            font-family: 'SFMono-Regular', Consolas, monospace;
            font-size: 10px;
            word-break: break-all;
        }}

        @media (max-width: 768px) {{
            .meta-bar {{ flex-direction: column; gap: 6px; }}
            table {{ font-size: 12px; }}
            thead th, tbody td {{ padding: 8px; }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Premium Reduction Options</h1>
            <div class="subtitle">Consumer Duty Explanation — FCA PS22/9</div>
        </div>
        <div class="meta-bar">
            <span>Reference: <strong>{ref}</strong></span>
            <span>Product: <strong>{product.title()}</strong></span>
            <span>Model: <strong>{model_version}</strong></span>
            <span>Generated: <strong>{self._generated_at[:10]}</strong></span>
            <span>Current premium: <strong>£{self.current_premium:,.2f}/yr</strong></span>
        </div>
        <div class="card">
            <div class="intro">{intro_msg}</div>
            {no_options_msg}
            {table_section}
            <div class="footer">
                <div>
                    This explanation was generated automatically. Savings are estimates
                    based on the current rating model and may change at renewal.
                    Burning Cost Ltd · FCA Consumer Duty PS22/9
                </div>
                <div class="audit-hash">Audit hash: {audit_hash[:32]}...</div>
            </div>
        </div>
    </div>
</body>
</html>"""

    def __repr__(self) -> str:
        return (
            f"RecourseReport("
            f"policyholder_id={self.policyholder_id!r}, "
            f"current_premium={self.current_premium:.2f}, "
            f"n_options={len(self.actions)})"
        )


def _is_numeric(v: Any) -> bool:
    try:
        float(v)
        return True
    except (TypeError, ValueError):
        return False
